[metadata]
creation_date = "2025/04/07"
list_name = "TestShareList"
rule_ids = ["4ed8e743-3af3-4503-b710-497c16a53ed9"]
rule_names = ["rere"]
updated_date = "2024/07/10"

[[exceptions]]
[exceptions.container]
description = "Dac Vuln Scanners"
list_id = "dbc9b368-5d39-41fa-9a16-bfcb995fc866"
name = "vulnerability_scanners"
namespace_type = "single"
tags = []
type = "detection"

[[exceptions.items]]
comments = []
description = "Exception list item"
list_id = "dbc9b368-5d39-41fa-9a16-bfcb995fc866"
item_id = "7c823cd0-ca30-46ba-af35-3633219eed1f"
name = "qualys_scanners"
namespace_type = "single"
tags = []
type = "simple"

[[exceptions.items.entries]]
field = "source.ip"
type = "match"
operator = "included"
value = "192.168.1.10"


