[metadata]
creation_date = "2025/04/02"
maturity = "development"
updated_date = "2025/04/02"

[rule]
author = ["ben"]
description = "test"
language = "kuery"
name = "dac1"
risk_score = 50
rule_id = "4132c06e-f80f-4f9a-a165-fa476615d99e"
severity = "low"
type = "query"

query = '''
event.category : *
'''

