[metadata]
creation_date = "2025/04/02"
maturity = "development"
updated_date = "2025/04/02"

[rule]
author = ["ben"]
description = "Test Dac "
language = "kuery"
name = "Dac Kql Test"
risk_score = 50
rule_id = "25a948fb-714a-4cdc-bea8-626d19929a8b"
severity = "medium"
type = "query"

query = '''
event.category : "authentication" and "user.name" : "root"
'''

