[metadata]
creation_date = "2025/04/07"
maturity = "development"
updated_date = "2025/04/07"

[rule]
index = ["logs-*"]
enabled = "true"
author = ["test"]
exceptions_list = ["7c823cd0-ca30-46ba-af35-3633219eed1f"]
description = "derer"
language = "kuery"
name = "rere"
risk_score = 50
rule_id = "4ed8e743-3af3-4503-b710-497c16a53ed9"
severity = "high"
type = "query"

query = '''
event.category : "network"
'''

