[metadata]
creation_date = "2025/04/03"
maturity = "development"
updated_date = "2025/04/03"

[rule]
author = ["ben d"]
description = "test"
language = "kuery"
name = "Suspicious Authentication"
risk_score = 50
rule_id = "7d06e503-6d64-4957-916c-b4fb354c3d40"
severity = "high"
type = "query"

query = '''
event.category : "authentication" and event.outcome : "failed"
'''

