[metadata]
creation_date = "2025/04/03"
maturity = "development"
updated_date = "2025/04/03"

[rule]
author = ["Elastic"]
description = "Test Dac"
language = "kuery"
name = "Suspicious Authentication"
risk_score = 50
rule_id = "1ffa9080-c7e9-4f8d-b501-8e925c614477"
severity = "medium"
index = "logs-*"
type = "query"

query = '''
event.category : "authentication" and event.outcome : "failure"
'''

