[metadata]
creation_date = "2025/04/03"
maturity = "development"
updated_date = "2025/04/03"

[rule]
author = ["ben"]
description = "Test "
language = "kuery"
name = "suspicious authentication"
risk_score = 50
rule_id = "44e671b7-e4b2-44e7-8850-3ef9569b8e51"
severity = "high"
type = "query"

query = '''
event.category : "network"
'''

