[metadata]
creation_date = "2025/04/03"
maturity = "development"
updated_date = "2025/04/03"

[rule]
author = ["Ben D"]
description = "Test DAC"
language = "kuery"
name = "Suspicious Authentication"
risk_score = 50
rule_id = "1d2e961e-a667-44a3-ab6a-66719d9d558e"
severity = "high"
type = "query"

query = '''
event.category : "authentication" and event.outcome : "failed"
'''

