[metadata]
creation_date = "2025/04/03"
maturity = "development"
updated_date = "2025/04/03"

[rule]
author = ["Ben D"]
enable = "true"
description = """
Identifies Suspicious Authentications.
"""
false_positives = ["Legitimate exchange system administration activity."]
from = "now-9m"
index = [
    "logs-*"]
language = "kuery"
license = "Elastic License v2"
name = "Suspicious Authentication Detected"
note = """## TBD.
"""
references = [
    "https://www.elastic.co/",
    "https://www.elastic.co/"
]
risk_score = 47
rule_id = "6aace640-e631-4870-ba8e-5fdda09325db"
severity = "medium"
tags = [
    "Domain: Endpoint",
    "OS: Windows",
]
timestamp_override = "event.ingested"
type = "query"

query = '''
event.category : "authentication" and event.outcome : "failure"
'''

[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1078"
name = "Valid Accounts"
reference = "https://attack.mitre.org/techniques/T1078/"
[[rule.threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"

