[metadata]
creation_date = "2025/04/03"
maturity = "development"
updated_date = "2025/04/03"

[rule]
author = ["ben"]
description = "test"
language = "kuery"
name = "suspicious authentication"
risk_score = 50
rule_id = "bdd2111e-de82-4efe-a9d4-5e99a9122c0b"
severity = "high"
type = "query"

query = '''
event.category : "authentication" and event.outcome : "failed"
'''

