[metadata]
creation_date = "2025/04/03"
maturity = "development"
updated_date = "2025/04/03"

[rule]
author = ["Ben D"]
description = """
Identifies Suspicious Authentication
"""
false_positives = ["Legitimate exchange system administration activity."]
from = "now-9m"
index = [
    "logs-*"]
language = "kuery"
license = "Elastic License v2"
name = "Suspicious Authentication Detected"
note = """## TBD.
"""
references = [
    "https://www.elastic.co/",
    "https://www.elastic.co/"
]
risk_score = 47
rule_id = "6aace640-e631-4870-ba8e-5fdda09325db"
severity = "medium"
enabled = "true"
tags = [
    "Domain: Endpoint",
    "OS: Windows",
]
type = "query"

query = '''
event.category : "authentication" and event.outcome : "failure" and user.name : "adminfake"
'''

