name: Log Generator

on:

  workflow_dispatch:
    inputs:
      space:
        description: 'Kibana space to use (dev or prod)'
        required: false
        default: 'dac-dev'

jobs:

  generate-auth-logs:
    name: Generate Authentication Logs & Send to Elastic SIEM
   # if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: pip install elasticsearch requests faker

      - name: Run Authentication Log Generator
        env:
          ELASTIC_URL: "${{ secrets.ELASTIC_URL }}"
          ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
        run: python scripts/windows_logs_gen.py

 
