name: Log Generator
on:
  workflow_dispatch:
    inputs:
      space:
        description: 'Kibana space to use (dev or prod)'
        required: false
        default: 'dac-dev'
env:
    ELASTIC_URL: "https://demo-security.es.us-west2.gcp.elastic-cloud.com"
    ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
jobs:
  generate-auth-logs:
    name: Generate Authentication Logs & Send to Elastic SIEM
 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: pip install elasticsearch requests faker

      - name: Run Authentication Log Generator
     
        run: |
          python scripts/windows_logs_gen.py

  
